const CardStorageMurloc = new Map<String, any>();

import BaiGeErGeGuoWang from "./BaiGeErGeGuoWang.ts";
import BenBoErBa from "./BenBoErBa.ts";
import CaiKuaiYuRen from "./CaiKuaiYuRen.ts";
import ChaoXiXianZhiMoGeEr from "./ChaoXiXianZhiMoGeEr.ts";
import CuXinDeTunJiZhe from "./CuXinDeTunJiZhe.ts";
import DiYinTiQinYuRen from "./DiYinTiQinYuRen.ts";
import FuChuShiZhang from "./FuChuShiZhang.ts";
import GeJuYiShuJia from "./GeJuYiShuJia.ts";
import HanGuangXianZhi from "./HanGuangXianZhi.ts";
import HeChangYuRen from "./HeChangYuRen.ts";
import JuEDongQiYuRen from "./JuEDongQiYuRen.ts";
import ManYuChiHou from "./ManYuChiHou.ts";
import RongYanYuRen from "./RongYanYuRen.ts";
import ShanQiYuYanZhe from "./ShanQiYuYanZhe.ts";
import ShiTangLieRen from "./ShiTangLieRen.ts";
import TaDe from "./TaDe.ts";
import TanTuTiaoTiaoYu from "./TanTuTiaoTiaoYu.ts";
import XiaoXiaYan from "./XiaoXiaYan.ts";
import XiongEDeMiShiZhe from "./XiongEDeMiShiZhe.ts";
import XunBaoYuRen from "./XunBaoYuRen.ts";
import YouGe_SaLongShiZhanZhe from "./YouGe_SaLongShiZhanZhe.ts";
import ZhaoZeQianFeng from "./ZhaoZeQianFeng.ts";
CardStorageMurloc.set("BaiGeErGeGuoWang", BaiGeErGeGuoWang);
CardStorageMurloc.set("BenBoErBa", BenBoErBa);
CardStorageMurloc.set("CaiKuaiYuRen", CaiKuaiYuRen);
CardStorageMurloc.set("ChaoXiXianZhiMoGeEr", ChaoXiXianZhiMoGeEr);
CardStorageMurloc.set("CuXinDeTunJiZhe", CuXinDeTunJiZhe);
CardStorageMurloc.set("DiYinTiQinYuRen", DiYinTiQinYuRen);
CardStorageMurloc.set("FuChuShiZhang", FuChuShiZhang);
CardStorageMurloc.set("GeJuYiShuJia", GeJuYiShuJia);
CardStorageMurloc.set("HanGuangXianZhi", HanGuangXianZhi);
CardStorageMurloc.set("HeChangYuRen", HeChangYuRen);
CardStorageMurloc.set("JuEDongQiYuRen", JuEDongQiYuRen);
CardStorageMurloc.set("ManYuChiHou", ManYuChiHou);
CardStorageMurloc.set("RongYanYuRen", RongYanYuRen);
CardStorageMurloc.set("ShanQiYuYanZhe", ShanQiYuYanZhe);
CardStorageMurloc.set("ShiTangLieRen", ShiTangLieRen);
CardStorageMurloc.set("TaDe", TaDe);
CardStorageMurloc.set("TanTuTiaoTiaoYu", TanTuTiaoTiaoYu);
CardStorageMurloc.set("XiaoXiaYan", XiaoXiaYan);
CardStorageMurloc.set("XiongEDeMiShiZhe", XiongEDeMiShiZhe);
CardStorageMurloc.set("XunBaoYuRen", XunBaoYuRen);
CardStorageMurloc.set("YouGe_SaLongShiZhanZhe", YouGe_SaLongShiZhanZhe);
CardStorageMurloc.set("ZhaoZeQianFeng", ZhaoZeQianFeng);

export default CardStorageMurloc
