const CardStorageMurloc = new Map<String, any>();

import AoJiaoTieNiu from "./AoJiaoTieNiu.ts";
import BaoBaoBao from "./BaoBaoBao.ts";
import BaZhuaJuGuaiDeChuShou from "./BaZhuaJuGuaiDeChuShou.ts";
import BaZhuaJuGuaiShuoChangJuanWang from "./BaZhuaJuGuaiShuoChangJuanWang.ts";
import BianChiZheTeLiGaoLei from "./BianChiZheTeLiGaoLei.ts";
import BingHaoQiangLiMengLang from "./BingHaoQiangLiMengLang.ts";
import DaQianXie from "./DaQianXie.ts";
import EnZuoSiDeYu from "./EnZuoSiDeYu.ts";
import EZuMaTeDeChuXu from "./EZuMaTeDeChuXu.ts";
import FengKuangDeHouZi from "./FengKuangDeHouZi.ts";
import HengMingFengNiao from "./HengMingFengNiao.ts";
import HuoBaoXiongJi from "./HuoBaoXiongJi.ts";
import JiaChong from "./JiaChong.ts";
import JianJiaoJiuXing from "./JianJiaoJiuXing.ts";
import JiBianJiaChong from "./JiBianJiaChong.ts";
import JinKeGuWeiGui from "./JinKeGuWeiGui.ts";
import JiXieMaJu from "./JiXieMaJu.ts";
import JiXieMuMa from "./JiXieMuMa.ts";
import JiXieXiaoMa from "./JiXieXiaoMa.ts";
import JuDaDeJinGangYingWu from "./JuDaDeJinGangYingWu.ts";
import JuLangGeDeLin from "./JuLangGeDeLin.ts";
import KeDuoShouBaoBao from "./KeDuoShouBaoBao.ts";
import KuanHouDeTuoLu from "./KuanHouDeTuoLu.ts";
import MoRenBao from "./MoRenBao.ts";
import NuHuoFeiYang from "./NuHuoFeiYang.ts";
import ShaYuEr from "./ShaYuEr.ts";
import TaMuZuo from "./TaMuZuo.ts";
import WaSheng from "./WaSheng.ts";
import WeiWuZhanJuMaiKeSiWei from "./WeiWuZhanJuMaiKeSiWei.ts";
import XiongBaBa from "./XiongBaBa.ts";
import XiongMaMa from "./XiongMaMa.ts";
import XuanCaiZhuoTianZhe from "./XuanCaiZhuoTianZhe.ts";
import YinSenJuMang from "./YinSenJuMang.ts";
import YinYuBaiE from "./YinYuBaiE.ts";
import YinYuChuE from "./YinYuChuE.ts";
import YiZhongZuanDiChong from "./YiZhongZuanDiChong.ts";
import YouLingZhongQuan from "./YouLingZhongQuan.ts";
import YouNianLeiXiang from "./YouNianLeiXiang.ts";
import ZhongJinShuShuangTouFeiLong from "./ZhongJinShuShuangTouFeiLong.ts";
CardStorageMurloc.set("AoJiaoTieNiu", AoJiaoTieNiu);
CardStorageMurloc.set("BaoBaoBao", BaoBaoBao);
CardStorageMurloc.set("BaZhuaJuGuaiDeChuShou", BaZhuaJuGuaiDeChuShou);
CardStorageMurloc.set("BaZhuaJuGuaiShuoChangJuanWang", BaZhuaJuGuaiShuoChangJuanWang);
CardStorageMurloc.set("BianChiZheTeLiGaoLei", BianChiZheTeLiGaoLei);
CardStorageMurloc.set("BingHaoQiangLiMengLang", BingHaoQiangLiMengLang);
CardStorageMurloc.set("DaQianXie", DaQianXie);
CardStorageMurloc.set("EnZuoSiDeYu", EnZuoSiDeYu);
CardStorageMurloc.set("EZuMaTeDeChuXu", EZuMaTeDeChuXu);
CardStorageMurloc.set("FengKuangDeHouZi", FengKuangDeHouZi);
CardStorageMurloc.set("HengMingFengNiao", HengMingFengNiao);
CardStorageMurloc.set("HuoBaoXiongJi", HuoBaoXiongJi);
CardStorageMurloc.set("JiaChong", JiaChong);
CardStorageMurloc.set("JianJiaoJiuXing", JianJiaoJiuXing);
CardStorageMurloc.set("JiBianJiaChong", JiBianJiaChong);
CardStorageMurloc.set("JinKeGuWeiGui", JinKeGuWeiGui);
CardStorageMurloc.set("JiXieMaJu", JiXieMaJu);
CardStorageMurloc.set("JiXieMuMa", JiXieMuMa);
CardStorageMurloc.set("JiXieXiaoMa", JiXieXiaoMa);
CardStorageMurloc.set("JuDaDeJinGangYingWu", JuDaDeJinGangYingWu);
CardStorageMurloc.set("JuLangGeDeLin", JuLangGeDeLin);
CardStorageMurloc.set("KeDuoShouBaoBao", KeDuoShouBaoBao);
CardStorageMurloc.set("KuanHouDeTuoLu", KuanHouDeTuoLu);
CardStorageMurloc.set("MoRenBao", MoRenBao);
CardStorageMurloc.set("NuHuoFeiYang", NuHuoFeiYang);
CardStorageMurloc.set("ShaYuEr", ShaYuEr);
CardStorageMurloc.set("TaMuZuo", TaMuZuo);
CardStorageMurloc.set("WaSheng", WaSheng);
CardStorageMurloc.set("WeiWuZhanJuMaiKeSiWei", WeiWuZhanJuMaiKeSiWei);
CardStorageMurloc.set("XiongBaBa", XiongBaBa);
CardStorageMurloc.set("XiongMaMa", XiongMaMa);
CardStorageMurloc.set("XuanCaiZhuoTianZhe", XuanCaiZhuoTianZhe);
CardStorageMurloc.set("YinSenJuMang", YinSenJuMang);
CardStorageMurloc.set("YinYuBaiE", YinYuBaiE);
CardStorageMurloc.set("YinYuChuE", YinYuChuE);
CardStorageMurloc.set("YiZhongZuanDiChong", YiZhongZuanDiChong);
CardStorageMurloc.set("YouLingZhongQuan", YouLingZhongQuan);
CardStorageMurloc.set("YouNianLeiXiang", YouNianLeiXiang);
CardStorageMurloc.set("ZhongJinShuShuangTouFeiLong", ZhongJinShuShuangTouFeiLong);

export default CardStorageMurloc
