const CardStorageMachine = new Map<String, any>();

import BaoBaoJiQiRen from ".//BaoBaoJiQiRen";
import BaoFeiFeiPinHuiShouJi from ".//BaoFeiFeiPinHuiShouJi";
import ChaoChaoJiQiRen from ".//ChaoChaoJiQiRen";
import ChaoChaoMoZu from ".//ChaoChaoMoZu";
import ChiQuPuYiJi from ".//ChiQuPuYiJi";
import CuiMianJiQiRen from ".//CuiMianJiQiRen";
import DuoMianFuZhuWuRenJi from ".//DuoMianFuZhuWuRenJi";
import JiXiangMaJu from ".//JiXiangMaJu";
import JiXieMuMa from ".//JiXieMuMa";
import JiXieXiaoMa from ".//JiXieXiaoMa";
import JiXingB_BOXQuanShou from ".//JiXingB_BOXQuanShou";
import KanGeErDeXueTu from ".//KanGeErDeXueTu";
import LiangChanXingKongHeJi from ".//LiangChanXingKongHeJi";
import OuMiQiePoHuaiZhe from ".//OuMiQiePoHuaiZhe";
import PengPengFeiChe from ".//PengPengFeiChe";
import PianZheJiQiRen from ".//PianZheJiQiRen";
import ShouFengQinJiQiRen from ".//ShouFengQinJiQiRen";
import SiShen4000Xing from ".//SiShen4000Xing";
import WeiXingJiQiRen from ".//WeiXingJiQiRen";
import WeiXingMuNaiYi from ".//WeiXingMuNaiYi";
import ZiShiYingLuZhang from ".//ZiShiYingLuZhang";
CardStorageMachine.set(BaoBaoJiQiRen.name, BaoBaoJiQiRen);
CardStorageMachine.set(BaoFeiFeiPinHuiShouJi.name, BaoFeiFeiPinHuiShouJi);
CardStorageMachine.set(ChaoChaoJiQiRen.name, ChaoChaoJiQiRen);
CardStorageMachine.set(ChaoChaoMoZu.name, ChaoChaoMoZu);
CardStorageMachine.set(ChiQuPuYiJi.name, ChiQuPuYiJi);
CardStorageMachine.set(CuiMianJiQiRen.name, CuiMianJiQiRen);
CardStorageMachine.set(DuoMianFuZhuWuRenJi.name, DuoMianFuZhuWuRenJi);
CardStorageMachine.set(JiXiangMaJu.name, JiXiangMaJu);
CardStorageMachine.set(JiXieMuMa.name, JiXieMuMa);
CardStorageMachine.set(JiXieXiaoMa.name, JiXieXiaoMa);
CardStorageMachine.set(JiXingB_BOXQuanShou.name, JiXingB_BOXQuanShou);
CardStorageMachine.set(KanGeErDeXueTu.name, KanGeErDeXueTu);
CardStorageMachine.set(LiangChanXingKongHeJi.name, LiangChanXingKongHeJi);
CardStorageMachine.set(OuMiQiePoHuaiZhe.name, OuMiQiePoHuaiZhe);
CardStorageMachine.set(PengPengFeiChe.name, PengPengFeiChe);
CardStorageMachine.set(PianZheJiQiRen.name, PianZheJiQiRen);
CardStorageMachine.set(ShouFengQinJiQiRen.name, ShouFengQinJiQiRen);
CardStorageMachine.set(SiShen4000Xing.name, SiShen4000Xing);
CardStorageMachine.set(WeiXingJiQiRen.name, WeiXingJiQiRen);
CardStorageMachine.set(WeiXingMuNaiYi.name, WeiXingMuNaiYi);
CardStorageMachine.set(ZiShiYingLuZhang.name, ZiShiYingLuZhang);
export default CardStorageMachine
