const CardStorageMachine = new Map<String, any>();

import BaoBaoJiQiRenV28 from ".//BaoBaoJiQiRen";
import BaoFeiFeiPinHuiShouJiV28 from ".//BaoFeiFeiPinHuiShouJi";
import ChaoChaoJiQiRenV28 from ".//ChaoChaoJiQiRen";
import ChaoChaoMoZuV28 from ".//ChaoChaoMoZu";
import ChiQuPuYiJiV28 from ".//ChiQuPuYiJi";
import CuiMianJiQiRenV28 from ".//CuiMianJiQiRen";
import DuoMianFuZhuWuRenJiV28 from ".//DuoMianFuZhuWuRenJi";
import JiXiangMaJuV28 from ".//JiXiangMaJu";
import JiXieMuMaV28 from ".//JiXieMuMa";
import JiXieXiaoMaV28 from ".//JiXieXiaoMa";
import JiXingB_BOXQuanShouV28 from ".//JiXingB_BOXQuanShou";
import KanGeErDeXueTuV28 from ".//KanGeErDeXueTu";
import LiangChanXingKongHeJiV28 from ".//LiangChanXingKongHeJi";
import OuMiQiePoHuaiZheV28 from ".//OuMiQiePoHuaiZhe";
import PengPengFeiCheV28 from ".//PengPengFeiChe";
import PianZheJiQiRenV28 from ".//PianZheJiQiRen";
import ShouFengQinJiQiRenV28 from ".//ShouFengQinJiQiRen";
import SiShen4000XingV28 from ".//SiShen4000Xing";
import WeiXingJiQiRenV28 from ".//WeiXingJiQiRen";
import WeiXingMuNaiYiV28 from ".//WeiXingMuNaiYi";
import ZiShiYingLuZhangV28 from ".//ZiShiYingLuZhang";

CardStorageMachine.set("BaoBaoJiQiRen", BaoBaoJiQiRenV28);
CardStorageMachine.set("BaoFeiFeiPinHuiShouJi", BaoFeiFeiPinHuiShouJiV28);
CardStorageMachine.set("ChaoChaoJiQiRen", ChaoChaoJiQiRenV28);
CardStorageMachine.set("ChaoChaoMoZu", ChaoChaoMoZuV28);
CardStorageMachine.set("ChiQuPuYiJi", ChiQuPuYiJiV28);
CardStorageMachine.set("CuiMianJiQiRen", CuiMianJiQiRenV28);
CardStorageMachine.set("DuoMianFuZhuWuRenJi", DuoMianFuZhuWuRenJiV28);
CardStorageMachine.set("JiXiangMaJu", JiXiangMaJuV28);
CardStorageMachine.set("JiXieMuMa", JiXieMuMaV28);
CardStorageMachine.set("JiXieXiaoMa", JiXieXiaoMaV28);
CardStorageMachine.set("JiXingB_BOXQuanShou", JiXingB_BOXQuanShouV28);
CardStorageMachine.set("KanGeErDeXueTu", KanGeErDeXueTuV28);
CardStorageMachine.set("LiangChanXingKongHeJi", LiangChanXingKongHeJiV28);
CardStorageMachine.set("OuMiQiePoHuaiZhe", OuMiQiePoHuaiZheV28);
CardStorageMachine.set("PengPengFeiChe", PengPengFeiCheV28);
CardStorageMachine.set("PianZheJiQiRen", PianZheJiQiRenV28);
CardStorageMachine.set("ShouFengQinJiQiRen", ShouFengQinJiQiRenV28);
CardStorageMachine.set("SiShen4000Xing", SiShen4000XingV28);
CardStorageMachine.set("WeiXingJiQiRen", WeiXingJiQiRenV28);
CardStorageMachine.set("WeiXingMuNaiYi", WeiXingMuNaiYiV28);
CardStorageMachine.set("ZiShiYingLuZhang", ZiShiYingLuZhangV28);
export default CardStorageMachine
