const CardStorageFishPeople = new Map<String, any>();

import BaiGeErGeGuoWangV28 from ".//BaiGeErGeGuoWang";
import ChaoXiXianZhiMoGeErV28 from ".//ChaoXiXianZhiMoGeEr";
import CuXinDeTunJiZheV28 from ".//CuXinDeTunJiZhe";
import DiDiaoTiQinYuRenV28 from ".//DiDiaoTiQinYuRen";
import GeJuYiShuJiaV28 from ".//GeJuYiShuJia";
import HeChangYuRenV28 from ".//HeChangYuRen";
import LieYanFeiYuV28 from ".//LieYanFeiYu";
import ManYuChiHouV28 from ".//ManYuChiHou";
import MoLaKeLiSiV28 from ".//MoLaKeLiSi";
import NanChanDeShiShiYuRenV28 from ".//NanChanDeShiShiYuRen";
import ShiTangLieRenV28 from ".//ShiTangLieRen";
import TaDeV28 from ".//TaDe";
import XiaoXiaYanV28 from ".//XiaoXiaYan";
import XieQiDaoHangYuanV28 from ".//XieQiDaoHangYuan";
import XiongEDeMiShiZheV28 from ".//XiongEDeMiShiZhe";
import XunBaoYuRenV28 from ".//XunBaoYuRen";
import ZaiKuaiYuRenV28 from ".//ZaiKuaiYuRen";
import ZhaoZeQianFengV28 from ".//ZhaoZeQianFeng";
CardStorageFishPeople.set("BaiGeErGeGuoWang", BaiGeErGeGuoWangV28);
CardStorageFishPeople.set("ChaoXiXianZhiMoGeEr", ChaoXiXianZhiMoGeErV28);
CardStorageFishPeople.set("CuXinDeTunJiZhe", CuXinDeTunJiZheV28);
CardStorageFishPeople.set("DiDiaoTiQinYuRen", DiDiaoTiQinYuRenV28);
CardStorageFishPeople.set("GeJuYiShuJia", GeJuYiShuJiaV28);
CardStorageFishPeople.set("HeChangYuRen", HeChangYuRenV28);
CardStorageFishPeople.set("LieYanFeiYu", LieYanFeiYuV28);
CardStorageFishPeople.set("ManYuChiHou", ManYuChiHouV28);
CardStorageFishPeople.set("MoLaKeLiSi", MoLaKeLiSiV28);
CardStorageFishPeople.set("NanChanDeShiShiYuRen", NanChanDeShiShiYuRenV28);
CardStorageFishPeople.set("ShiTangLieRen", ShiTangLieRenV28);
CardStorageFishPeople.set("TaDe", TaDeV28);
CardStorageFishPeople.set("XiaoXiaYan", XiaoXiaYanV28);
CardStorageFishPeople.set("XieQiDaoHangYuan", XieQiDaoHangYuanV28);
CardStorageFishPeople.set("XiongEDeMiShiZhe", XiongEDeMiShiZheV28);
CardStorageFishPeople.set("XunBaoYuRen", XunBaoYuRenV28);
CardStorageFishPeople.set("ZaiKuaiYuRen", ZaiKuaiYuRenV28);
CardStorageFishPeople.set("ZhaoZeQianFeng", ZhaoZeQianFengV28);

export default CardStorageFishPeople
