const CardStorage = new Map<String, any>();

import FenNuBianZhiZhe from "./FenNuBianZhiZhe";
import JiEDeFuMo from "./JiEDeFuMo";
import JiXieJiaLaKeSuSi from "./JiXieJiaLaKeSuSi";
import JunTuanJianGong from "./JunTuanJianGong";
import KongJuHuZiWang from "./KongJuHuZiWang";
import LingHunHuiSuZhe from "./LingHunHuiSuZhe";
import PiaoFuGuanChaZhe from "./PiaoFuGuanChaZhe";
import QiGuiDaJiLeShou from "./QiGuiDaJiLeShou";
import SaGeLaSiDeYongShi from "./SaGeLaSiDeYongShi";
import TanShiDeWuZuEr from "./TanShiDeWuZuEr";
import TiaoShiMoQuan from "./TiaoShiMoQuan";
import TiKeDiAoSaoSi from "./TiKeDiAoSaoSi";
import WuDaoWangZiMaKeZhaEr from "./WuDaoWangZiMaKeZhaEr";
import XiaoGui from "./XiaoGui";
import XiaoGuiQiuTu from "./XiaoGuiQiuTu";
import XieNengYuanSu from "./XieNengYuanSu";
import XinLingNiMo from "./XinLingNiMo";
import XiongEDeXieNengYouLong from "./XiongEDeXieNengYouLong";
import XiXueDiYuQuan from "./XiXueDiYuQuan";
import YiJiaoTuSiSeLa from "./YiJiaoTuSiSeLa";
import ZaoDongQiZhaZhe from "./ZaoDongQiZhaZhe";

CardStorage.set(FenNuBianZhiZhe.name, FenNuBianZhiZhe);
CardStorage.set(JiEDeFuMo.name, JiEDeFuMo);
CardStorage.set(JiXieJiaLaKeSuSi.name, JiXieJiaLaKeSuSi);
CardStorage.set(JunTuanJianGong.name, JunTuanJianGong);
CardStorage.set(KongJuHuZiWang.name, KongJuHuZiWang);
CardStorage.set(LingHunHuiSuZhe.name, LingHunHuiSuZhe);
CardStorage.set(PiaoFuGuanChaZhe.name, PiaoFuGuanChaZhe);
CardStorage.set(QiGuiDaJiLeShou.name, QiGuiDaJiLeShou);
CardStorage.set(SaGeLaSiDeYongShi.name, SaGeLaSiDeYongShi);
CardStorage.set(TanShiDeWuZuEr.name, TanShiDeWuZuEr);
CardStorage.set(TiaoShiMoQuan.name, TiaoShiMoQuan);
CardStorage.set(TiKeDiAoSaoSi.name, TiKeDiAoSaoSi);
CardStorage.set(WuDaoWangZiMaKeZhaEr.name, WuDaoWangZiMaKeZhaEr);
CardStorage.set(XiaoGui.name, XiaoGui);
CardStorage.set(XiaoGuiQiuTu.name, XiaoGuiQiuTu);
CardStorage.set(XieNengYuanSu.name, XieNengYuanSu);
CardStorage.set(XinLingNiMo.name, XinLingNiMo);
CardStorage.set(XiongEDeXieNengYouLong.name, XiongEDeXieNengYouLong);
CardStorage.set(XiXueDiYuQuan.name, XiXueDiYuQuan);
CardStorage.set(YiJiaoTuSiSeLa.name, YiJiaoTuSiSeLa);
CardStorage.set(ZaoDongQiZhaZhe.name, ZaoDongQiZhaZhe);

import BaoBaoJiQiRen from "./machine/BaoBaoJiQiRen";
import BaoFeiFeiPinHuiShouJi from "./machine/BaoFeiFeiPinHuiShouJi";
import ChaoChaoJiQiRen from "./machine/ChaoChaoJiQiRen";
import ChaoChaoMoZu from "./machine/ChaoChaoMoZu";
import ChiQuPuYiJi from "./machine/ChiQuPuYiJi";
import CuiMianJiQiRen from "./machine/CuiMianJiQiRen";
import DuoMianFuZhuWuRenJi from "./machine/DuoMianFuZhuWuRenJi";
import JiXieMuMa from "./machine/JiXieMuMa";
import JiXingB_BOXQuanShou from "./machine/JiXingB_BOXQuanShou";
import KanGeErDeXueTu from "./machine/KanGeErDeXueTu";
import LiangChanXingKongHeJi from "./machine/LiangChanXingKongHeJi";
import OuMiQiePoHuaiZhe from "./machine/OuMiQiePoHuaiZhe";
import PengPengFeiChe from "./machine/PengPengFeiChe";
import PianZheJiQiRen from "./machine/PianZheJiQiRen";
import ShouFengQinJiQiRen from "./machine/ShouFengQinJiQiRen";
import SiShen4000Xing from "./machine/SiShen4000Xing";
import WeiXingMuNaiYi from "./machine/WeiXingMuNaiYi";
import ZiShiYingLuZhang from "./machine/ZiShiYingLuZhang";

CardStorage.set(BaoBaoJiQiRen.name, BaoBaoJiQiRen);
CardStorage.set(BaoFeiFeiPinHuiShouJi.name, BaoFeiFeiPinHuiShouJi);
CardStorage.set(ChaoChaoJiQiRen.name, ChaoChaoJiQiRen);
CardStorage.set(ChaoChaoMoZu.name, ChaoChaoMoZu);
CardStorage.set(ChiQuPuYiJi.name, ChiQuPuYiJi);
CardStorage.set(CuiMianJiQiRen.name, CuiMianJiQiRen);
CardStorage.set(DuoMianFuZhuWuRenJi.name, DuoMianFuZhuWuRenJi);
CardStorage.set(JiXieMuMa.name, JiXieMuMa);
CardStorage.set(JiXingB_BOXQuanShou.name, JiXingB_BOXQuanShou);
CardStorage.set(KanGeErDeXueTu.name, KanGeErDeXueTu);
CardStorage.set(LiangChanXingKongHeJi.name, LiangChanXingKongHeJi);
CardStorage.set(OuMiQiePoHuaiZhe.name, OuMiQiePoHuaiZhe);
CardStorage.set(PengPengFeiChe.name, PengPengFeiChe);
CardStorage.set(PianZheJiQiRen.name, PianZheJiQiRen);
CardStorage.set(ShouFengQinJiQiRen.name, ShouFengQinJiQiRen);
CardStorage.set(SiShen4000Xing.name, SiShen4000Xing);
CardStorage.set(WeiXingMuNaiYi.name, WeiXingMuNaiYi);
CardStorage.set(ZiShiYingLuZhang.name, ZiShiYingLuZhang);
export default CardStorage
