const CardStorage = new Map<String, any>();

import FenNuBianZhiZhe from "./kyoma/FenNuBianZhiZhe";
import JiEDeFuMo from "./kyoma/JiEDeFuMo";
import JiXieJiaLaKeSuSi from "./kyoma/JiXieJiaLaKeSuSi";
import JunTuanJianGong from "./kyoma/JunTuanJianGong";
import KongJuHuZiWang from "./kyoma/KongJuHuZiWang";
import LingHunHuiSuZhe from "./kyoma/LingHunHuiSuZhe";
import PiaoFuGuanChaZhe from "./kyoma/PiaoFuGuanChaZhe";
import QiGuiDaJiLeShou from "./kyoma/QiGuiDaJiLeShou";
import SaGeLaSiDeYongShi from "./kyoma/SaGeLaSiDeYongShi";
import TanShiDeWuZuEr from "./kyoma/TanShiDeWuZuEr";
import TiaoShiMoQuan from "./kyoma/TiaoShiMoQuan";
import TiKeDiAoSaoSi from "./kyoma/TiKeDiAoSaoSi";
import WuDaoWangZiMaKeZhaEr from "./kyoma/WuDaoWangZiMaKeZhaEr";
import XiaoGui from "./kyoma/XiaoGui";
import XiaoGuiQiuTu from "./kyoma/XiaoGuiQiuTu";
import XieNengYuanSu from "./kyoma/XieNengYuanSu";
import XinLingNiMo from "./kyoma/XinLingNiMo";
import XiongEDeXieNengYouLong from "./kyoma/XiongEDeXieNengYouLong";
import XiXueDiYuQuan from "./kyoma/XiXueDiYuQuan";
import YiJiaoTuSiSeLa from "./kyoma/YiJiaoTuSiSeLa";
import ZaoDongQiZhaZhe from "./kyoma/ZaoDongQiZhaZhe";

CardStorage.set(FenNuBianZhiZhe.name, FenNuBianZhiZhe);
CardStorage.set(JiEDeFuMo.name, JiEDeFuMo);
CardStorage.set(JiXieJiaLaKeSuSi.name, JiXieJiaLaKeSuSi);
CardStorage.set(JunTuanJianGong.name, JunTuanJianGong);
CardStorage.set(KongJuHuZiWang.name, KongJuHuZiWang);
CardStorage.set(LingHunHuiSuZhe.name, LingHunHuiSuZhe);
CardStorage.set(PiaoFuGuanChaZhe.name, PiaoFuGuanChaZhe);
CardStorage.set(QiGuiDaJiLeShou.name, QiGuiDaJiLeShou);
CardStorage.set(SaGeLaSiDeYongShi.name, SaGeLaSiDeYongShi);
CardStorage.set(TanShiDeWuZuEr.name, TanShiDeWuZuEr);
CardStorage.set(TiaoShiMoQuan.name, TiaoShiMoQuan);
CardStorage.set(TiKeDiAoSaoSi.name, TiKeDiAoSaoSi);
CardStorage.set(WuDaoWangZiMaKeZhaEr.name, WuDaoWangZiMaKeZhaEr);
CardStorage.set(XiaoGui.name, XiaoGui);
CardStorage.set(XiaoGuiQiuTu.name, XiaoGuiQiuTu);
CardStorage.set(XieNengYuanSu.name, XieNengYuanSu);
CardStorage.set(XinLingNiMo.name, XinLingNiMo);
CardStorage.set(XiongEDeXieNengYouLong.name, XiongEDeXieNengYouLong);
CardStorage.set(XiXueDiYuQuan.name, XiXueDiYuQuan);
CardStorage.set(YiJiaoTuSiSeLa.name, YiJiaoTuSiSeLa);
CardStorage.set(ZaoDongQiZhaZhe.name, ZaoDongQiZhaZhe);

import BaoBaoJiQiRen from "./machine/BaoBaoJiQiRen";
import BaoFeiFeiPinHuiShouJi from "./machine/BaoFeiFeiPinHuiShouJi";
import ChaoChaoJiQiRen from "./machine/ChaoChaoJiQiRen";
import ChaoChaoMoZu from "./machine/ChaoChaoMoZu";
import ChiQuPuYiJi from "./machine/ChiQuPuYiJi";
import CuiMianJiQiRen from "./machine/CuiMianJiQiRen";
import DuoMianFuZhuWuRenJi from "./machine/DuoMianFuZhuWuRenJi";
import JiXiangMaJu from "./machine/JiXiangMaJu";
import JiXieMuMa from "./machine/JiXieMuMa";
import JiXieXiaoMa from "./machine/JiXieXiaoMa";
import JiXingB_BOXQuanShou from "./machine/JiXingB_BOXQuanShou";
import KanGeErDeXueTu from "./machine/KanGeErDeXueTu";
import LiangChanXingKongHeJi from "./machine/LiangChanXingKongHeJi";
import OuMiQiePoHuaiZhe from "./machine/OuMiQiePoHuaiZhe";
import PengPengFeiChe from "./machine/PengPengFeiChe";
import PianZheJiQiRen from "./machine/PianZheJiQiRen";
import ShouFengQinJiQiRen from "./machine/ShouFengQinJiQiRen";
import SiShen4000Xing from "./machine/SiShen4000Xing";
import WeiXingJiQiRen from "./machine/WeiXingJiQiRen";
import WeiXingMuNaiYi from "./machine/WeiXingMuNaiYi";
import ZiShiYingLuZhang from "./machine/ZiShiYingLuZhang";

CardStorage.set(BaoBaoJiQiRen.name, BaoBaoJiQiRen);
CardStorage.set(BaoFeiFeiPinHuiShouJi.name, BaoFeiFeiPinHuiShouJi);
CardStorage.set(ChaoChaoJiQiRen.name, ChaoChaoJiQiRen);
CardStorage.set(ChaoChaoMoZu.name, ChaoChaoMoZu);
CardStorage.set(ChiQuPuYiJi.name, ChiQuPuYiJi);
CardStorage.set(CuiMianJiQiRen.name, CuiMianJiQiRen);
CardStorage.set(DuoMianFuZhuWuRenJi.name, DuoMianFuZhuWuRenJi);
CardStorage.set(JiXiangMaJu.name, JiXiangMaJu);
CardStorage.set(JiXieMuMa.name, JiXieMuMa);
CardStorage.set(JiXieXiaoMa.name, JiXieXiaoMa);
CardStorage.set(JiXingB_BOXQuanShou.name, JiXingB_BOXQuanShou);
CardStorage.set(KanGeErDeXueTu.name, KanGeErDeXueTu);
CardStorage.set(LiangChanXingKongHeJi.name, LiangChanXingKongHeJi);
CardStorage.set(OuMiQiePoHuaiZhe.name, OuMiQiePoHuaiZhe);
CardStorage.set(PengPengFeiChe.name, PengPengFeiChe);
CardStorage.set(PianZheJiQiRen.name, PianZheJiQiRen);
CardStorage.set(ShouFengQinJiQiRen.name, ShouFengQinJiQiRen);
CardStorage.set(SiShen4000Xing.name, SiShen4000Xing);
CardStorage.set(WeiXingJiQiRen.name, WeiXingJiQiRen);
CardStorage.set(WeiXingMuNaiYi.name, WeiXingMuNaiYi);
CardStorage.set(ZiShiYingLuZhang.name, ZiShiYingLuZhang);

export default CardStorage
