const CardStorageSpell = new Map<String, any>();
import AiZeLiTeQiangHua28 from "./AiZeLiTeQiangHua";
CardStorageSpell.set("AiZeLiTeQiangHua", AiZeLiTeQiangHua28);
import BuLaiEnDeEnHui28 from "./BuLaiEnDeEnHui";
CardStorageSpell.set("BuLaiEnDeEnHui", BuLaiEnDeEnHui28);
import ChenShuiZheZhiYong28 from "./ChenShuiZheZhiYong";
CardStorageSpell.set("ChenShuiZheZhiYong", ChenShuiZheZhiYong28);
import DengLongHuoGuang28 from "./DengLongHuoGuang";
CardStorageSpell.set("DengLongHuoGuang", DengLongHuoGuang28);
import DianJinZhiChu28 from "./DianJinZhiChu";
CardStorageSpell.set("DianJinZhiChu", DianJinZhiChu28);
import DingJianHaoJiu28 from "./DingJianHaoJiu";
CardStorageSpell.set("DingJianHaoJiu", DingJianHaoJiu28);
import FangYuZheDeYiShi28 from "./FangYuZheDeYiShi";
CardStorageSpell.set("FangYuZheDeYiShi", FangYuZheDeYiShi28);
import FuMoLianSuo28 from "./FuMoLianSuo";
CardStorageSpell.set("FuMoLianSuo", FuMoLianSuo28);
import FuZuZhiZhang28 from "./FuZuZhiZhang";
CardStorageSpell.set("FuZuZhiZhang", FuZuZhiZhang28);
import GaoGuaiKu28 from "./GaoGuaiKu";
CardStorageSpell.set("GaoGuaiKu", GaoGuaiKu28);
import HaMiuErYiShiDeFaZhang28 from "./HaMiuErYiShiDeFaZhang";
CardStorageSpell.set("HaMiuErYiShiDeFaZhang", HaMiuErYiShiDeFaZhang28);
import HuiXiangPaoXiao28 from "./HuiXiangPaoXiao";
CardStorageSpell.set("HuiXiangPaoXiao", HuiXiangPaoXiao28);
import HuJiaChuBei28 from "./HuJiaChuBei";
CardStorageSpell.set("HuJiaChuBei", HuJiaChuBei28);
import HuoBanZhuLi28 from "./HuoBanZhuLi";
CardStorageSpell.set("HuoBanZhuLi", HuoBanZhuLi28);
import JianLiJianShi28 from "./JianLiJianShi";
CardStorageSpell.set("JianLiJianShi", JianLiJianShi28);
import JiuGuanBi28 from "./JiuGuanBi";
CardStorageSpell.set("JiuGuanBi", JiuGuanBi28);
import KuaiSuLiuLan28 from "./KuaiSuLiuLan";
CardStorageSpell.set("KuaiSuLiuLan", KuaiSuLiuLan28);
import LieTouZhaoPin28 from "./LieTouZhaoPin";
CardStorageSpell.set("LieTouZhaoPin", LieTouZhaoPin28);
import LuanFaDeChaJu28 from "./LuanFaDeChaJu";
CardStorageSpell.set("LuanFaDeChaJu", LuanFaDeChaJu28);
import LuMangTouZi28 from "./LuMangTouZi";
CardStorageSpell.set("LuMangTouZi", LuMangTouZi28);
import MingYunZhiE28 from "./MingYunZhiE";
CardStorageSpell.set("MingYunZhiE", MingYunZhiE28);
import PinMingFaJue28 from "./PinMingFaJue";
CardStorageSpell.set("PinMingFaJue", PinMingFaJue28);
import QiangGu28 from "./QiangGu";
CardStorageSpell.set("QiangGu", QiangGu28);
import ShanLiangDeJieZhi28 from "./ShanLiangDeJieZhi";
CardStorageSpell.set("ShanLiangDeJieZhi", ShanLiangDeJieZhi28);
import ShenFenJieXiao28 from "./ShenFenJieXiao";
CardStorageSpell.set("ShenFenJieXiao", ShenFenJieXiao28);
import ShengZhangYiShi28 from "./ShengZhangYiShi";
CardStorageSpell.set("ShengZhangYiShi", ShengZhangYiShi28);
import ShenShengZengLi28 from "./ShenShengZengLi";
CardStorageSpell.set("ShenShengZengLi", ShenShengZengLi28);
import ShenZhongTouZi28 from "./ShenZhongTouZi";
CardStorageSpell.set("ShenZhongTouZi", ShenZhongTouZi28);
import ShunXiHuoLi28 from "./ShunXiHuoLi";
CardStorageSpell.set("ShunXiHuoLi", ShunXiHuoLi28);
import TiTuSiDeZhuangBei28 from "./TiTuSiDeZhuangBei";
CardStorageSpell.set("TiTuSiDeZhuangBei", TiTuSiDeZhuangBei28);
import WanMeiXingXiang28 from "./WanMeiXingXiang";
CardStorageSpell.set("WanMeiXingXiang", WanMeiXingXiang28);
import WeiMianWangYuanJing28 from "./WeiMianWangYuanJing";
CardStorageSpell.set("WeiMianWangYuanJing", WeiMianWangYuanJing28);
import XiangJiaoGuoPan28 from "./XiangJiaoGuoPan";
CardStorageSpell.set("XiangJiaoGuoPan", XiangJiaoGuoPan28);
import YiWaiZhiGuo28 from "./YiWaiZhiGuo";
CardStorageSpell.set("YiWaiZhiGuo", YiWaiZhiGuo28);
import YouShiYaZhi28 from "./YouShiYaZhi";
CardStorageSpell.set("YouShiYaZhi", YouShiYaZhi28);
import YuanShiZhiZhang28 from "./YuanShiZhiZhang";
CardStorageSpell.set("YuanShiZhiZhang", YuanShiZhiZhang28);
import YuDingYiTi28 from "./YuDingYiTi";
CardStorageSpell.set("YuDingYiTi", YuDingYiTi28);
import ZhaoMuXinRen28 from "./ZhaoMuXinRen";
CardStorageSpell.set("ZhaoMuXinRen", ZhaoMuXinRen28);
import ZhuChuZhenXuan28 from "./ZhuChuZhenXuan";
CardStorageSpell.set("ZhuChuZhenXuan", ZhuChuZhenXuan28);
import ZiFu28 from "./ZiFu";
CardStorageSpell.set("ZiFu", ZiFu28);
import ZiRanZhuFu28 from "./ZiRanZhuFu";
CardStorageSpell.set("ZiRanZhuFu", ZiRanZhuFu28);
import ZuanTanYuanYou28 from "./ZuanTanYuanYou";
CardStorageSpell.set("ZuanTanYuanYou", ZuanTanYuanYou28);
export default CardStorageSpell